### ISSUE TITLE
[Question] Is this the future repo for System.CommandLine

### ISSUE THREAD

**Issue by shaggygi** [dotnet/CliCommandLineParser#2]
Is [this repo](https://github.com/dotnet/corefxlab/tree/master/src/System.CommandLine) moving here?

**Comment by piotrpMSFT** [comment]
This command line parser is currently designed specifically for the dotnet CLI. As it matures, it might make sense for it to be reconsiled for System.CommandLine. For the time being, however, the dotnet CLI has been the primary design consideration for this library and it's not clear if the library will be viable for other projects in its current state.

**Comment by shaggygi** [comment]
@piotrpMSFT Okay, gotcha.  Thanks for the insight.  When I first came across this repo, I was thinking it was a generic CLI.  It does seem like this .NET Core CLI would use the System.CommandLine from CoreFxLabs as the method of how commands, arguments, etc. are parsed/processed.  Doing so could flesh out features, bugs and such from the System.CommandLine API allowing it to gain traction for other CLI tooling.

Thanks again for reply.  Closing issue.

**Comment by piotrpMSFT** [comment]
@shaggygi we started down that path, but found that we would need a System.CommandLine v2 to get the capabilities we need for the `dotnet cli`. Instead of creating a bunch of confusion for folks currently using System.CommandLine, we want to experiment here and see if we can get to a design we're really happy with. Once there, we can look at reconciliation. Do feel free to take a look at the work being done here and provide feedback. I'd be curious to see what you think!

**Comment by shaggygi** [comment]
@piotrpMSFT I'll keep watch on the progress (to learn along the way).  This sounds like a good approach where a final solution for System.CommandLine could be used later.
